// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXaVt2AivD6IPLH8Hi-bWyUnQhc0ymIAU',
    appId: '1:175762979363:web:99a8fef7be50a00af84f96',
    messagingSenderId: '175762979363',
    projectId: 'kazi-8c1b2',
    authDomain: 'kazi-8c1b2.firebaseapp.com',
    storageBucket: 'kazi-8c1b2.appspot.com',
    measurementId: 'G-D96N79ZG6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAN2TnedBpdpok7TGsqj1t8FJ4VLOYv7c',
    appId: '1:175762979363:android:f0faee7c9159a1c6f84f96',
    messagingSenderId: '175762979363',
    projectId: 'kazi-8c1b2',
    storageBucket: 'kazi-8c1b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfigByeoRoftPv9I_2SHlmhDGbRqZpUGY',
    appId: '1:175762979363:ios:314ae173a882fce8f84f96',
    messagingSenderId: '175762979363',
    projectId: 'kazi-8c1b2',
    storageBucket: 'kazi-8c1b2.appspot.com',
    iosClientId:
        '175762979363-1q432lfijt8p2v361n1ea8mcpmocorc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaziBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfigByeoRoftPv9I_2SHlmhDGbRqZpUGY',
    appId: '1:175762979363:ios:314ae173a882fce8f84f96',
    messagingSenderId: '175762979363',
    projectId: 'kazi-8c1b2',
    storageBucket: 'kazi-8c1b2.appspot.com',
    iosClientId:
        '175762979363-1q432lfijt8p2v361n1ea8mcpmocorc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaziBoard',
  );
}
